name: flutterosm
description: A new Flutter application.

publish_to: 'none'
version: '1.0.0'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.1.3
  # https://pub.flutter-io.cn/packages/dio
  dio: ^3.0.9
  flutter_easyrefresh: ^2.1.1
  flutter_screenutil: ^1.0.2
  fast_event_bus: ^1.0.1
  flutter_bmfutils: ^1.0.1
  flutter_picker_plugin: ^2.0.0
  flutter_bmfmap:
    git:
      url: 'https://gitee.com/LuHenChang/flutter_bmfmap-1.0.2.git'
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bdmap_location_flutter_plugin: ^0.0.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - imag/map_visible_marker.webp
    - imag/map_center.webp
    - imag/map_dl.webp
    - imag/map_fzebp.png
    - imag/map_location.webp
    - imag/map_tower.webp
    - imag/map_visible_all.webp
    - imag/map_visible_length.webp
    - imag/map_visible_marker.webp
    - imag/map_wx.webp
    - imag/map_zhanfang.webp
    - imag/main_gd.webp
    - imag/main_kyw.webp
    - imag/main_xiahu.webp
    - imag/map_location_selected.webp
    - imag/y_ty_hws.png
    - imag/y_ty_hwx.png
    - imag/map_tower.png
    - imag/c_ty_zsfhkg.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages